---
- hosts: ios               # 対象のホスト名・グループ名（inventory.iniで定義）
  gather_facts: false

  vars:
    # 設定するインターフェース
    interfraces:
      - name: GigabitEthernet1
        address: 172.16.1.254
        mask: 255.255.255.0
        description: hogehoge1      # ★任意の値に修正する
      - name: GigabitEthernet2
        address: 172.16.2.254
        mask: 255.255.255.0
        description: hogehoge2
    # 設定する Syslog サーバーのリスト
    syslog_servers:
      - 10.0.1.1
      - 10.0.1.2

  tasks:
    # コンフィグ生成タスク
    - name: generate config   # タスクの名前
      copy:                   # 使用するモジュール名
        content: "{{ lookup('template', 'config.j2') }}"    # 元ネタテンプレートファイル名
        dest: config.txt      # 生成先コンフィグファイル名
    
    # Cisco IOS ネットワーク機器に対してコンフィグを投入するタスク
    # ※ただしサンプルのため実行しない
    - name: set config        # タスクの名前
      ios_config:             # 使用するモジュール名
        src: config.txt       # コンフィグファイル名
      tags: never             # 実行しないための指定

