---
- hosts: ios               # 対象のホスト名・グループ名（inventory.iniで定義）
  gather_facts: false

  vars:           
    ntp_servers:           # 設定する NTP サーバーのリスト
      - 10.0.1.1
      - 10.0.1.2
    syslog_servers:
      - 10.0.1.3
      - 10.0.1.4

  tasks:
    # コンフィグ生成タスク
    - name: generate config   # タスクの名前
      copy:                   # 使用するモジュール名
        content: "{{ lookup('template', 'config.j2') }}"    # 元ネタテンプレートファイル名
        dest: config.txt      # 生成先コンフィグファイル名
    
    # Cisco IOS ネットワーク機器に対してコンフィグを投入するタスク
    # ※ただしサンプルのため実行しない
    - name: set config        # タスクの名前
      ios_config:             # 使用するモジュール名
        src: config.txt       # コンフィグファイル名
      tags: never             # 実行しないための指定

